# Generated by Django 2.2.12 on 2020-06-05 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='chatroom created on')),
            ],
        ),
        migrations.CreateModel(
            name='ChatboxMessage',
            fields=[
                ('chat_room', models.CharField(max_length=1000)),
                ('user_name', models.CharField(max_length=1000)),
                ('msg_num', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='chatbox.ChatRoom')),
            ],
        ),
    ]
