# Generated by Django 2.2.12 on 2020-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current_state',
            field=models.IntegerField(db_column='current_state', default=1),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
