# Generated by Django 2.2.12 on 2020-06-05 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_auto_20200605_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
